# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dS7psz82Qi0KncVS7q3DpcURbA3fGuDe
"""

!pip install scikit-learn pandas matplotlib seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.decomposition import PCA

from sklearn.cluster import KMeans, AgglomerativeClustering, MeanShift

from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

data = load_wine()
X = pd.DataFrame(data.data, columns=data.feature_names)

print("Dataset Shape:", X.shape)
X.head()

scaler = StandardScaler()
power = PowerTransformer()

# Raw
X_raw = X.copy()

# Normalized
X_norm = scaler.fit_transform(X)

# Transformed
X_trans = power.fit_transform(X)

# PCA
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X)

# Transform + Normalize
X_tn = scaler.fit_transform(X_trans)

# Transform + Normalize + PCA
X_tnpca = pca.fit_transform(X_tn)

datasets = {
    "Raw": X_raw,
    "Normalized": X_norm,
    "Transformed": X_trans,
    "PCA": X_pca,
    "T+N": X_tn,
    "T+N+PCA": X_tnpca
}

def evaluate(X, labels):
    if len(set(labels)) < 2:
        return None, None, None

    sil = silhouette_score(X, labels)
    ch = calinski_harabasz_score(X, labels)
    db = davies_bouldin_score(X, labels)

    return sil, ch, db

results = []

for name, data in datasets.items():

    for k in [3, 4, 5]:
        kmeans = KMeans(n_clusters=k, random_state=42)
        labels = kmeans.fit_predict(data)

        sil, ch, db = evaluate(data, labels)

        results.append(["KMeans", name, k, sil, ch, db])


    for k in [3, 4, 5]:
        hc = AgglomerativeClustering(n_clusters=k)
        labels = hc.fit_predict(data)

        sil, ch, db = evaluate(data, labels)

        results.append(["Hierarchical", name, k, sil, ch, db])


    ms = MeanShift()
    labels = ms.fit_predict(data)

    sil, ch, db = evaluate(data, labels)

    results.append(["MeanShift", name, "auto", sil, ch, db])

df_results = pd.DataFrame(results, columns=[
    "Algorithm", "Preprocessing", "K", "Silhouette", "Calinski-Harabasz", "Davies-Bouldin"
])

df_results

df_results.to_csv("clustering_results.csv", index=False)

plt.figure(figsize=(12,6))
sns.barplot(data=df_results, x="Preprocessing", y="Silhouette", hue="Algorithm")
plt.xticks(rotation=45)
plt.title("Silhouette Score Comparison")
plt.show()

plt.figure(figsize=(12,6))
sns.barplot(data=df_results, x="Preprocessing", y="Calinski-Harabasz", hue="Algorithm")
plt.xticks(rotation=45)
plt.title("Calinski-Harabasz Score")
plt.show()

plt.figure(figsize=(12,6))
sns.barplot(data=df_results, x="Preprocessing", y="Davies-Bouldin", hue="Algorithm")
plt.xticks(rotation=45)
plt.title("Davies-Bouldin Score")
plt.show()

pca2 = PCA(n_components=2)
X_vis = pca2.fit_transform(X_norm)

kmeans = KMeans(n_clusters=3, random_state=42)
labels = kmeans.fit_predict(X_vis)

plt.figure(figsize=(8,6))
plt.scatter(X_vis[:,0], X_vis[:,1], c=labels, cmap='viridis')
plt.title("KMeans Clustering (PCA 2D)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

